# This is a workflow to test and deploy our backend core.

name: Test backendcore.

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  LOCAL_MONGO: 1
  KOUKOU_HOME: /home/runner/work/BackEndCore/BackEndCore/
  PYTHONPATH: /home/runner/work/BackEndCore/BackEndCore/
  # MONGO_PASSWD: ${{secrets.MONGO_PASSWD}}
  
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    environment: pa-deploy

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Install necessary packages.
        run: make dev_env

      - name: Run Python tests.
        run: make all_tests

